### ISSUE TITLE
Multi-core analysis with OpenSeesSP

### ISSUE THREAD

**Issue by rsamtaslimi** [OpenSees/OpenSees#956] opened 2022-08-16 17:47 UTC
Dear Dr. Scott

As you may remember, a couple of weeks ago, I reported an issue with OpenSeesSP regarding the Prestress material (Issue #900). After you checked the source code, it appeared that something was missing, and you fixed it. I really appreciate your prompt response and consideration. Since then, that error does not pop up anymore, and I could run my model using SP with one core. However, another error comes up when I try to use more than one core to break down the model. I tried the SP on two different machines compiled by two different groups. One in our server at UNR and the other on Design-safe. Both groups have compiled the SP via the latest source code available on GitHub. In order to make sure that the error was not from my model, I tried to run a 2D 20-story building model with fiber elements which have been analyzed with multi-cores on the previous version of the SP successfully. But even for this model, if I use more than one core with the latest SP, the analysis fails while it can be done using only one core. This issue has been checked with the SP on our server at UNR and the one compiled by people at Design-safe. The error of the model with Prestress material is as follows. Would you please look into this and share your thoughts? 
 
I can also share the error that I got while I tried to run the building model with more than one core if that could be helpful.

DomainPartitioner::partition() - Start
Input Error: Incorrect objective type.
DomainPartitioner::partition - Successful partition. Now redistributing data accordingly.
  * Identifying components to transfer.
     + Elements.
     + Nodes.
     + Boundary Nodes.
[petrone:917542] *** Process received signal ***
[petrone:917542] Signal: Segmentation fault (11)
[petrone:917542] Signal code: Address not mapped (1)
[petrone:917542] Failing at address: 0x560ada78d8a0
[petrone:917542] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7fa192e9f980]
[petrone:917542] [ 1] OpenSeesP(+0xcfb4e1)[0x560d7f6b04e1]
[petrone:917542] [ 2] OpenSeesP(+0xcf778c)[0x560d7f6ac78c]
[petrone:917542] [ 3] OpenSeesP(+0x1323b7)[0x560d7eae73b7]
[petrone:917542] [ 4] OpenSeesP(+0x13d21f)[0x560d7eaf221f]
[petrone:917542] [ 5] /usr/lib/x86_64-linux-gnu/libtcl8.6.so(TclInvokeStringCommand+0x79)[0x7fa193c3dff9]
[petrone:917542] [ 6] /usr/lib/x86_64-linux-gnu/libtcl8.6.so(TclNRRunCallbacks+0x46)[0x7fa193c40406]
[petrone:917542] [ 7] /usr/lib/x86_64-linux-gnu/libtcl8.6.so(+0x3bfba)[0x7fa193c40fba]
[petrone:917542] [ 8] /usr/lib/x86_64-linux-gnu/libtcl8.6.so(Tcl_FSEvalFileEx+0x268)[0x7fa193cfada8]
[petrone:917542] [ 9] /usr/lib/x86_64-linux-gnu/libtcl8.6.so(Tcl_EvalFile+0x27)[0x7fa193cf9637]
[petrone:917542] [10] OpenSeesP(+0x11fab8)[0x560d7ead4ab8]
[petrone:917542] [11] OpenSeesP(+0x1115ee)[0x560d7eac65ee]
[petrone:917542] [12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fa192abdc87]
[petrone:917542] [13] OpenSeesP(+0x11f63a)[0x560d7ead463a]
[petrone:917542] *** End of error message ***

**Comment by silviamazzoni** [comment] 2022-08-16 18:14
I can't help with SP, but what do you mean by Fiber Elements?

**Comment by rsamtaslimi** [comment] 2022-08-16 18:19
Dear Dr. Mazzoni

Sorry for the unclear explanation. I meant Displacement-based Fiber-section elements.

**Comment by silviamazzoni** [comment] 2022-08-16 18:24
Can I ask you why you made this modeling choice? Have you also assigned multiple IPs to the elements?

**Comment by rsamtaslimi** [comment] 2022-08-16 18:29
That was just an example model I used to check if the OpenSeesSP fails due to an error in my bridge model or if the issue is somewhere else. Unfortunately, I am not sure about the multiple IPs as I have not generated that building model, but I checked that model using multiple-core on another machine with the previous version of SP, and it went well to the end with no issue. 

And yes, the building model has Fiber sections for both beam and column elements.

**Comment by silviamazzoni** [comment] 2022-08-16 18:41
thank you for the answer. again, my question was not about sp, but to have an understand of the types of models people who need sp are building.

**Comment by rsamtaslimi** [comment] 2022-08-16 18:49
Not a problem. The model that I am using for my research is a long-span suspension bridge with over 10k elements and that is why I need to use SP to improve the analysis time with the help of parallel computing.

**Comment by mhscott** [comment] 2022-08-22 04:55
I think it's an issue with the parallel numberer, not OpenSeesSP or whatever "OpenSeesP" is

**Comment by fmckenna** [comment] 2022-09-12 16:35
no. the problem is elsewhere.

**Comment by mhscott** [comment] 2022-11-23 15:35
Closing. Start a new issue if necessary.

**Closed by mhscott** 2022-11-23 15:35 UTC
